from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_env: str = "development"
    database_url: str = "sqlite:///./signal_lab.db"
    jwt_secret: str = "development-only-change-me"
    jwt_expire_minutes: int = 30
    cors_origins: str = "http://localhost:8080"
    # ICICI Direct Breeze API (https://pypi.org/project/breeze-connect/). breeze_session_token
    # expires roughly every 24h / at midnight and must be regenerated by logging in at
    # https://api.icicidirect.com/apiuser/login?api_key=<breeze_api_key> -- it is not a
    # "set once" secret like the other two.
    breeze_api_key: str | None = None
    breeze_api_secret: str | None = None
    breeze_session_token: str | None = None
    alert_poll_seconds: int = 60
    # Off by default: an enabled strategy makes the poller call the licensed
    # provider on a fixed interval, unattended, on every server start. That
    # should be an explicit choice (counts against Breeze's rate limits,
    # 100/min & 5000/day), not something that starts happening the first time
    # someone runs `uvicorn` after setting up their .env.
    alerts_scheduler_enabled: bool = False

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    @property
    def cors_origin_list(self) -> list[str]:
        return [item.strip() for item in self.cors_origins.split(",") if item.strip()]


@lru_cache
def get_settings() -> Settings:
    return Settings()
